/* Generated By:JavaCC: Do not edit this line. phpConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface phpConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 5;
  /** RegularExpression Id. */
  int PLUS = 6;
  /** RegularExpression Id. */
  int MINUS = 7;
  /** RegularExpression Id. */
  int MULTIPLY = 8;
  /** RegularExpression Id. */
  int DIVIDE = 9;
  /** RegularExpression Id. */
  int EQ = 10;
  /** RegularExpression Id. */
  int INC = 11;
  /** RegularExpression Id. */
  int DEC = 12;
  /** RegularExpression Id. */
  int CAL = 13;
  /** RegularExpression Id. */
  int ANDOR = 14;
  /** RegularExpression Id. */
  int VS = 15;
  /** RegularExpression Id. */
  int START = 16;
  /** RegularExpression Id. */
  int END = 17;
  /** RegularExpression Id. */
  int SEMICO = 18;
  /** RegularExpression Id. */
  int OPENB = 19;
  /** RegularExpression Id. */
  int CLOSEB = 20;
  /** RegularExpression Id. */
  int OPENZ = 21;
  /** RegularExpression Id. */
  int CLOSEZ = 22;
  /** RegularExpression Id. */
  int Q = 23;
  /** RegularExpression Id. */
  int D = 24;
  /** RegularExpression Id. */
  int ONENINE = 25;
  /** RegularExpression Id. */
  int ZERO = 26;
  /** RegularExpression Id. */
  int DIGIT = 27;
  /** RegularExpression Id. */
  int CHAR = 28;
  /** RegularExpression Id. */
  int READLINE = 29;
  /** RegularExpression Id. */
  int SWITCH = 30;
  /** RegularExpression Id. */
  int CASE = 31;
  /** RegularExpression Id. */
  int DEF = 32;
  /** RegularExpression Id. */
  int IF = 33;
  /** RegularExpression Id. */
  int ELSE = 34;
  /** RegularExpression Id. */
  int ELSEIF = 35;
  /** RegularExpression Id. */
  int WHILE = 36;
  /** RegularExpression Id. */
  int DO = 37;
  /** RegularExpression Id. */
  int FOR = 38;
  /** RegularExpression Id. */
  int PRINT = 39;
  /** RegularExpression Id. */
  int RETURN = 40;
  /** RegularExpression Id. */
  int BREAK = 41;
  /** RegularExpression Id. */
  int BOOL = 42;
  /** RegularExpression Id. */
  int STRING = 43;
  /** RegularExpression Id. */
  int INT = 44;
  /** RegularExpression Id. */
  int VAR = 45;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<COMMENT>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"++\"",
    "\"--\"",
    "<CAL>",
    "<ANDOR>",
    "\"$\"",
    "\"<?php\"",
    "\"?>\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"\\\'\"",
    "\":\"",
    "<ONENINE>",
    "\"0\"",
    "<DIGIT>",
    "<CHAR>",
    "\"readline\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\"if\"",
    "\"else\"",
    "\"elseif\"",
    "\"while\"",
    "\"do\"",
    "\"for\"",
    "\"echo\"",
    "\"return\"",
    "\"break\"",
    "<BOOL>",
    "<STRING>",
    "<INT>",
    "<VAR>",
  };

}
